apiVersion: apps/v1
kind: Deployment
metadata:
  name: iamlive
  labels:
    app: iamlive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iamlive
  template:
    metadata:
      labels:
        app: iamlive
    spec:
      serviceAccountName: otterize-network-mapper
      containers:
        - name: iamlive
          image: 353146681200.dkr.ecr.us-east-1.amazonaws.com/iamlive:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 10080
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
---
apiVersion: v1
kind: Service
metadata:
  name: amazonaws
spec:
  selector:
    app: iamlive
  ports:
    - protocol: TCP
      port: 80
      targetPort: 10080
      name: http
    - protocol: TCP
      port: 443
      targetPort: 10443
      name: https
