apiVersion: apps/v1
kind: Deployment
metadata:
  name: iamlive
  labels:
    app: iamlive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iamlive
  template:
    metadata:
      labels:
        app: iamlive
    spec:
      containers:
        - name: proxy
          image: t/iamlive
          imagePullPolicy: Never
          ports:
            - containerPort: 10080
---
apiVersion: v1
kind: Service
metadata:
  name: iamlive
spec:
    selector:
        app: iamlive
    ports:
      - protocol: TCP
        port: 80
        targetPort: 10080